### ISSUE TITLE
minSdkVersion >= 15 ?

### ISSUE THREAD

**Issue by 1vvvf** [songhanghang/SmartHeaderFooterRecyclerview#2]
**VERSION:1.0.0**

> minSdkVersion 15

- 实际上,  可以向下兼容到API LEVEL 7. 
- 如果引用了android support 24.2.0 之后的版本, 可以兼容到9

如果minSdkVersion<15想引用Smart-HeaderFooter-RecyclerView, 目前只能在AndroidManifest.xml中指定
`<uses-sdk tools:overrideLibrary="com.headerfooter.songhang.library" />`

**Comment by songhanghang** [comment]
现在很多项目都不在支持4.01以下的系统，设备占用率已经很低

**Comment by songhanghang** [comment]
4.0以外机器不考虑
