### ISSUE TITLE
TYPE_HEADER=111? TYPE_FOOTER=112?

### ISSUE THREAD

**Issue by 1vvvf** [songhanghang/SmartHeaderFooterRecyclerview#3]
> public class SmartRecyclerAdapter extends RecyclerViewAdapterWrapper {
>   public static final int TYPE_HEADER = 111;
>   public static final int TYPE_FOOTER = 112;
> 

Type是不是可以考虑改成下面的:

> public class SmartRecyclerAdapter extends RecyclerViewAdapterWrapper {
>   public static final int TYPE_HEADER = -1;
>   public static final int TYPE_FOOTER = -2;
>

**Comment by songhanghang** [comment]
本来想设置极大值，不错的建议
